import type { Locale } from "./config";

const de = {
  label: "Individueller Website-Audit", date: "Geprüft am 08.09.2026", assessment: "Unsere Einschätzung",
  findings: "Was wir konkret ändern würden", observation: "Beobachtung", action: "Unser Vorschlag",
  priorities: "In dieser Reihenfolge würden wir starten", flow: "Ein klarerer Weg zur Anfrage",
  measurements: "Die technischen Messwerte", scores: ["Performance", "Zugänglichkeit", "Best Practices", "Technisches SEO"],
  metricLabels: ["Größtes sichtbares Element (LCP)", "Blockierte Reaktionszeit (TBT)", "Layoutverschiebungen (CLS)"],
  metricHelp: ["Bis 2,5 s gilt als gut. Hier ein simulierter Laborwert, keine reale Besucherstatistik.", "Zeit, in der lange Aufgaben den Hauptthread blockieren. Kein Ersatz für die reale Interaktionsmessung INP.", "Bis 0,10 gilt als gut. Der Wert hat keine Einheit und kann auch Cookie-Dialoge einschließen."],
  scoreNote: "Die vier Kategorien prüfen unterschiedliche technische Aspekte. Auch 100 Punkte sagen nichts darüber aus, wie überzeugend Inhalte sind oder wie viele Anfragen entstehen. Es gibt keine gemeinsame Gesamtnote.",
  incomplete: "Keine belastbaren Gesamtpunktzahlen: Beide Lighthouse-Läufe erreichten das Ladezeitlimit. Wir veröffentlichen deshalb keine daraus abgeleitete Performance-Bewertung.",
  methodology: "Prüfumfang und Einordnung", method: "Öffentliche Stichprobe mit Lighthouse 13.4.1, ergänzender Browser-, DOM- und bei Bedarf HTTP-Prüfung. Je URL ein für die angezeigten Werte verwendeter Mobiltest mit frischem Profil, 412 × 823 CSS-Pixeln, simuliertem Slow 4G und vierfacher CPU-Verlangsamung. Optionale Cookies wurden im Messlauf nicht bewusst akzeptiert. Werte können je Gerät, Verbindung und Einwilligungszustand abweichen.",
  search: "Direkte Google-Suchabfragen wurden versucht, aber durch Googles Bot-Prüfung blockiert. Ergänzend wurde eine allgemeine Websuche genutzt. Wir behaupten keine Google-Platzierung oder tatsächlich verlorene Anfragen. Es gab keinen Zugang zu Search Console, Analytics oder internen Buchungsdaten. Formulare und Buchungen wurden nicht abgesendet.",
  own: "Die geschäftlichen Auswirkungen sind unsere fachliche Einschätzung anhand der beobachteten Bedienung. Sie sind keine gemessenen Umsatzverluste. Empfehlungen sind Vorschläge für die Umsetzung; die Wirkung muss danach geprüft werden.",
  validationTitle: "Woran wir eine Verbesserung prüfen würden", validation: "Den wichtigsten Weg vom ersten Bildschirm bis zur Anfrage auf Handy und Computer durchgehen, zusätzlich mit Tastatur. Danach unter gleichen Bedingungen mehrere mobile Messläufe vergleichen. Anfrage- oder Buchungsquoten lassen sich erst mit rechtmäßig erhobenen Daten des Betreibers bewerten.",
  sources: "Quellen und geprüfte Stellen", sourcePage: "Geprüfte Website / Fachquelle", report: "Lokaler Lighthouse-Bericht und Browserprüfung vom 08.09.2026. Die konkreten Messwerte stehen oben; den Bericht stellen wir auf Anfrage bereit.",
  contactTitle: "Den ersten Schritt gemeinsam festlegen", contact: "Über diesen Audit sprechen", email: "E-Mail schreiben", privacy: "Datenschutz zur Briefansprache", websitePrivacy: "Datenschutz beim Websitebesuch", linkNote: "Für das angeschriebene Unternehmen erstellt. Der individuelle Link ist nicht passwortgeschützt und kann weitergegeben werden.",
  campaignTitle: "Datenschutz zur Briefansprache", campaignIntro: "Informationen nach Art. 14 DSGVO zu unseren individuellen Website-Audits und der einmaligen Briefwerbung.",
  privacySections: [
    ["Verantwortlicher und Kontakt", "Aleks Tsenov, suchio, Bergstraße 41, 65795 Hattersheim am Main, Deutschland. E-Mail: contact@suchio.net. Telefon: +49 176 42767348. Die vollständigen Informationen sind über diese Kontaktwege auch kostenfrei in Papierform erhältlich."],
    ["Welche Daten und aus welchen Quellen", "Wir verwenden veröffentlichte geschäftliche Website-Inhalte, Unternehmensbezeichnungen, geschäftliche Kontakt- und Adressangaben sowie technische Prüfbefunde. Die Anschriften stammen aus freiwillig veröffentlichten geschäftlichen Kontakt- oder Filialangaben sowie öffentlichen Branchenverzeichnissen. Pflichtangaben aus einem Impressum dienen nicht als Adressquelle für Briefwerbung. Die konkrete Anschriftquelle ist bei Bedarf auf Anfrage erhältlich. Die jeweilige Website ist im Brief und im individuellen Audit benannt; konkrete geprüfte Seiten stehen dort unter Quellen. Wir verwenden keine privaten Interessenprofile, besonderen Kategorien personenbezogener Daten oder angereicherten Kontaktlisten."],
    ["Zweck und Rechtsgrundlage", "Zweck ist die einmalige Vorstellung passender Website-Dienstleistungen anhand eines individuellen Audits. Soweit Informationen natürliche Personen betreffen, stützen wir die Verarbeitung auf Art. 6 Abs. 1 lit. f DSGVO. Unser Interesse liegt in einer sachlich passenden, begrenzten geschäftlichen Ansprache. Wir berücksichtigen die Erwartungen der Betroffenen, beschränken die Daten auf den geschäftlichen Bezug und beachten erkennbare Werbeablehnung. Eine öffentliche Fundstelle allein ersetzt keine Interessenabwägung."],
    ["Empfänger und Verarbeitung außerhalb des EWR", "Suchio druckt die Briefe am Kopierer im dm-Markt per USB oder Smartphone und verteilt sie. Ein Online-Druckdienst, CRM oder Adresshandel wird nicht eingesetzt. Für Recherche und Texterstellung dieser Aktion wird der OpenAI-Dienst Codex verwendet. Dafür werden ausgewählte veröffentlichte geschäftliche Inhalte und Anschriften an OpenAI übermittelt. Eine Verarbeitung außerhalb des EWR kann stattfinden. Weitere Angaben zur Verarbeitung durch OpenAI stehen in der unten verlinkten Datenschutzerklärung."],
    ["Bereitstellung des Audits", "Der Audit wird über einen individuellen, schwer erratbaren Link auf suchio.net bereitgestellt. Er wird nicht in Navigation oder Sitemap aufgenommen und erhält noindex. Dies ist kein Passwortschutz: Jeder mit dem Link kann den betreffenden Bericht lesen und weitergeben. Empfängeranschriften werden nicht auf der Auditseite veröffentlicht. Cloudflare hostet die Seiten und verarbeitet dabei Inhalte und technische Zugriffsdaten. Angaben zu Cloudflare, Übermittlungen und Websiteprotokollen enthält unsere allgemeine Datenschutzerklärung. Nur nach ausdrücklicher freiwilliger Zustimmung im Bericht wird ein bestätigter Aufruf gezählt. Ohne Zustimmung erfolgt keine Zählung. Details und Widerruf stehen im Abschnitt zur Audit-Auswertung."],
    ["Speicherdauer", "Die Arbeits- und Druckdateien sowie der Online-Audit werden nach Abschluss der Briefaktion einschließlich einer Rückmeldefrist von 30 Tagen entfernt, soweit kein konkreter Klärungs- oder Nachweisbedarf besteht. In diesem Fall verbleibt nur das Erforderliche. Für einen Werbewiderspruch bleibt die minimale Sperrinformation erhalten. Ein minimaler Vermerk aus Unternehmensname, Webdomain und Bearbeitungsstatus verhindert doppelte Akquise, solange dies dafür benötigt wird. Anschriften und Berichttexte gehören nicht zu diesem Vermerk. Die Löschung beim KI-Dienst wird gesondert veranlasst; dessen Aufbewahrungsregeln und gesetzliche Ausnahmen gelten zusätzlich. Bei einer anschließenden Anfrage gelten die in der allgemeinen Datenschutzerklärung genannten Zwecke und Fristen."],
    ["Ihre Rechte und Werbewiderspruch", "Sie können der Verarbeitung für Direktwerbung jederzeit ohne Begründung widersprechen. Eine Nachricht an contact@suchio.net oder die oben genannte Postanschrift genügt. Danach verwenden wir Ihre Daten nicht weiter für Direktwerbung. Unter den gesetzlichen Voraussetzungen bestehen Rechte auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung. Sie können sich bei einer Datenschutzaufsichtsbehörde beschweren, etwa beim Hessischen Beauftragten für Datenschutz und Informationsfreiheit. Es gibt keine automatisierte Entscheidung mit rechtlicher oder ähnlich erheblicher Wirkung."
    ]
  ]
};

type AuditUi = { [K in keyof typeof de]: typeof de[K] extends string ? string : string[][] | string[] };
const en = {
  label: "Individual website audit", date: "Checked on 8 September 2026", assessment: "Our assessment", findings: "What we would change", observation: "Observation", action: "Our proposal", priorities: "The order we would work in", flow: "A clearer enquiry journey",
  measurements: "Technical measurements", scores: ["Performance", "Accessibility", "Best Practices", "Technical SEO"], metricLabels: ["Largest Contentful Paint (LCP)", "Total Blocking Time (TBT)", "Cumulative Layout Shift (CLS)"], metricHelp: ["Up to 2.5 s is good. This is a simulated lab value, not a real visitor statistic.", "Time during which long tasks block the main thread. It does not replace real interaction measurement with INP.", "Up to 0.10 is good. The unitless value can include consent dialogs."],
  scoreNote: "These categories test different technical aspects. Even 100 points do not measure persuasive content or enquiry volume. There is no combined overall grade.", incomplete: "No reliable aggregate scores: both Lighthouse runs reached the loading time limit. We therefore do not publish a performance judgement derived from them.",
  methodology: "Scope and interpretation", method: "Public sample using Lighthouse 13.4.1, with browser, DOM and where needed HTTP checks. Each displayed result uses one mobile run per URL with a fresh profile, 412 × 823 CSS pixels, simulated Slow 4G and 4× CPU slowdown. Optional cookies were not deliberately accepted in the measurement run. Values can differ by device, connection and consent state.", search: "Direct Google searches were attempted but blocked by Google's bot challenge. General web search was also used. We claim no Google position or actual lost enquiries. We had no access to Search Console, Analytics or internal booking data. Forms and bookings were not submitted.", own: "Business implications are our professional assessment of observed usability, not measured revenue losses. Recommendations are implementation proposals whose effect needs checking afterwards.", validationTitle: "How we would verify improvements", validation: "Review the main journey from the first screen to an enquiry on phone and desktop, including keyboard use. Then compare several mobile runs under the same conditions. Enquiry or booking rates can only be assessed using lawfully collected operator data.", sources: "Sources and checked pages", sourcePage: "Checked website / technical source", report: "Local Lighthouse report and browser checks from 8 September 2026. Measurements are shown above; the report is available on request.", contactTitle: "Agree the first step together", contact: "Discuss this audit", email: "Send an email", privacy: "Privacy for postal outreach", websitePrivacy: "Website privacy", linkNote: "Prepared for the addressed business. This individual link is not password-protected and can be shared.", campaignTitle: "Privacy for postal outreach", campaignIntro: "Information under Article 14 GDPR about our individual website audits and one-off postal advertising.",
  privacySections: [
    ["Controller and contact", "Aleks Tsenov, suchio, Bergstraße 41, 65795 Hattersheim am Main, Germany. Email: contact@suchio.net. Phone: +49 176 42767348. You can also request this information on paper free of charge through these contacts."],
    ["Data and sources", "We use published business website content, company names, business contact and address details, and technical findings. Postal addresses come from voluntarily published business contact or store information and public business directories. Mandatory legal identification details are not used as address sources for postal advertising. The specific address source is available on request. The relevant website is named in the letter and individual audit, whose sources list the pages checked. We do not use private interest profiles, special categories of personal data or enriched contact lists."],
    ["Purpose and legal basis", "The purpose is a one-off introduction to relevant website services using an individual audit. Where information concerns natural persons, processing relies on Article 6(1)(f) GDPR. Our interest is limited, relevant business outreach. We consider reasonable expectations, minimise data to the business context and respect visible advertising objections. Public availability alone does not replace a balancing assessment."],
    ["Recipients and processing outside the EEA", "Suchio prints the letters at a copier in a dm store using USB or a smartphone and distributes them. No online printing service, CRM or address trading is used. The OpenAI service Codex is used to research and draft this campaign. Selected published business content and addresses are transmitted to OpenAI for that purpose. Processing outside the EEA may occur. Further information about OpenAI's processing is linked below."],
    ["Providing the audit", "The audit is available through an individual, hard-to-guess link on suchio.net, excluded from navigation and the sitemap and marked noindex. This is not password protection: anyone with the link can read and share that report. Recipient postal addresses are not published on audit pages. Cloudflare hosts the pages and processes content and technical access data. Our general privacy policy describes Cloudflare, transfers and website logs. Optional counting after explicit consent is described in the audit-measurement section. Without consent there is no such counting."],
    ["Retention", "Working files, print files and the online audit are removed after the campaign and a 30-day response period, unless a specific clarification or evidentiary need exists. Only necessary information is retained in that case. A minimal suppression record is kept for advertising objections. A minimal company-name, domain and processing-status record prevents duplicate outreach while needed for that purpose; it contains no postal addresses or report text. Deletion at the AI provider is requested separately and remains subject to its retention rules and legal exceptions. Subsequent enquiries follow the purposes and periods in our general privacy policy."],
    ["Your rights and advertising objections", "You can object to processing for direct marketing at any time without giving reasons. Email contact@suchio.net or write to the postal address above. We then stop using your data for direct marketing. Subject to legal conditions, you have rights of access, rectification, erasure and restriction. You may complain to a data protection authority, such as the Hessian Commissioner for Data Protection and Freedom of Information. There is no automated decision with legal or similarly significant effects."]
  ]
} satisfies AuditUi;

const fr = {
  label: "Audit individuel de site web", date: "Vérifié le 8 septembre 2026", assessment: "Notre appréciation", findings: "Ce que nous modifierions", observation: "Constat", action: "Notre proposition", priorities: "Dans cet ordre", flow: "Un parcours de demande plus clair",
  measurements: "Les mesures techniques", scores: ["Performance", "Accessibilité", "Bonnes pratiques", "SEO technique"], metricLabels: ["Plus grand élément visible (LCP)", "Temps de blocage total (TBT)", "Déplacements de contenu (CLS)"], metricHelp: ["Jusqu'à 2,5 s est considéré comme bon. Valeur de laboratoire simulée, pas une statistique de visiteurs réels.", "Durée pendant laquelle de longues tâches bloquent le fil principal. Ne remplace pas la mesure réelle des interactions INP.", "Jusqu'à 0,10 est considéré comme bon. Valeur sans unité pouvant inclure le dialogue de cookies."], scoreNote: "Les catégories évaluent différents aspects techniques. Même 100 points ne mesurent ni la qualité persuasive des textes ni le nombre de demandes. Il n'existe pas de note globale commune.", incomplete: "Pas de scores globaux fiables : les deux tests Lighthouse ont atteint la limite de chargement. Nous n'en tirons donc pas de jugement chiffré de performance.",
  methodology: "Périmètre et interprétation", method: "Échantillon public avec Lighthouse 13.4.1, complété par des contrôles navigateur, DOM et HTTP si nécessaire. Chaque résultat affiché provient d'un test mobile par URL avec un profil neuf, 412 × 823 pixels CSS, une connexion Slow 4G simulée et un processeur ralenti quatre fois. Les cookies facultatifs n'ont pas été acceptés volontairement pendant la mesure. Les résultats varient selon appareil, connexion et consentement.", search: "Des recherches Google directes ont été tentées mais bloquées par le contrôle anti-robot. Une recherche web générale a aussi été utilisée. Nous ne prétendons pas connaître un classement Google ou des demandes réellement perdues. Aucun accès à Search Console, Analytics ou aux réservations internes. Aucun formulaire ni réservation n'a été envoyé.", own: "Les conséquences commerciales sont notre appréciation professionnelle de l'utilisation observée, pas des pertes de chiffre d'affaires mesurées. Les recommandations sont des propositions dont l'effet doit être vérifié après réalisation.", validationTitle: "Comment vérifier les améliorations", validation: "Parcourir le chemin principal du premier écran à la demande sur téléphone et ordinateur, aussi au clavier. Comparer ensuite plusieurs tests mobiles dans les mêmes conditions. Les taux de demande ou de réservation nécessitent des données de l'exploitant collectées légalement.", sources: "Sources et pages contrôlées", sourcePage: "Site contrôlé / source technique", report: "Rapport Lighthouse local et vérification navigateur du 8 septembre 2026. Mesures ci-dessus ; rapport disponible sur demande.", contactTitle: "Définir ensemble la première étape", contact: "Discuter de cet audit", email: "Envoyer un e-mail", privacy: "Confidentialité du courrier publicitaire", websitePrivacy: "Confidentialité du site", linkNote: "Préparé pour l'entreprise destinataire. Ce lien individuel n'est pas protégé par mot de passe et peut être partagé.", campaignTitle: "Confidentialité du courrier publicitaire", campaignIntro: "Informations selon l'article 14 du RGPD sur nos audits individuels et cette action publicitaire postale ponctuelle.",
  privacySections: [
    ["Responsable et contact", "Aleks Tsenov, suchio, Bergstraße 41, 65795 Hattersheim am Main, Allemagne. E-mail : contact@suchio.net. Téléphone : +49 176 42767348. Ces coordonnées permettent aussi de demander gratuitement ces informations sur papier."],
    ["Données et sources", "Nous utilisons les contenus professionnels publiés, noms d’entreprises, coordonnées et adresses professionnelles ainsi que les constats techniques. Les adresses proviennent de coordonnées professionnelles ou de magasins publiées volontairement et d’annuaires professionnels publics. Les mentions légales obligatoires ne servent pas de source d’adresse pour la prospection postale. La source précise de l’adresse est disponible sur demande. Le site figure dans le courrier et l’audit individuel, qui énumère les pages examinées. Nous n’utilisons ni profils d’intérêts privés, ni catégories particulières de données, ni listes de contacts enrichies."],
    ["Finalité et base juridique", "La finalité est une présentation ponctuelle de services web pertinents au moyen d'un audit individuel. Pour les informations concernant des personnes physiques, nous nous fondons sur l'article 6, paragraphe 1, point f du RGPD. Notre intérêt est une prise de contact professionnelle limitée et pertinente. Nous considérons les attentes, limitons les données au contexte professionnel et respectons les refus de publicité visibles. La disponibilité publique seule ne remplace pas la mise en balance des intérêts."],
    ["Destinataires et traitement hors EEE", "Suchio imprime les courriers sur un copieur en magasin dm via USB ou smartphone et les distribue. Aucun service d’impression en ligne, CRM ou commerce d’adresses n’est utilisé. Le service Codex d’OpenAI sert à la recherche et à la rédaction de cette campagne. Certains contenus professionnels publiés et adresses sont transmis à OpenAI à cette fin. Un traitement hors EEE peut avoir lieu. Des informations complémentaires sur OpenAI figurent dans la politique liée ci-dessous."],
    ["Mise à disposition de l'audit", "L'audit est accessible par un lien individuel difficile à deviner sur suchio.net, absent de la navigation et du sitemap et marqué noindex. Ce n'est pas un mot de passe : toute personne ayant le lien peut lire et partager ce rapport. Les adresses postales des destinataires ne sont pas publiées sur ces pages. Cloudflare héberge les pages et traite contenus et données techniques d'accès. Notre politique générale décrit Cloudflare, les transferts et journaux du site. Une consultation est comptée uniquement après un consentement explicite et facultatif dans le rapport. Sans consentement, aucun comptage. Les détails et le retrait figurent dans la rubrique de mesure des audits."],
    ["Conservation", "Les fichiers de travail, d'impression et l'audit en ligne sont supprimés après l'action et un délai de réponse de 30 jours, sauf besoin précis de clarification ou de preuve. Seules les informations nécessaires restent alors conservées. Une trace minimale d’opposition est conservée. Un relevé minimal du nom d’entreprise, du domaine et du statut évite les doublons tant qu’il est nécessaire à cette fin ; il ne contient ni adresse postale ni texte de rapport. La suppression auprès du fournisseur d'IA est demandée séparément et reste soumise à ses règles et exceptions légales. Les demandes ultérieures suivent les finalités et délais de notre politique générale."],
    ["Droits et opposition publicitaire", "Vous pouvez vous opposer à tout moment, sans motif, au traitement pour prospection. Écrivez à contact@suchio.net ou à l'adresse postale ci-dessus. Vos données ne seront alors plus utilisées pour cette finalité. Sous les conditions légales, vous disposez des droits d'accès, rectification, effacement et limitation. Vous pouvez saisir une autorité de contrôle, par exemple le commissaire à la protection des données et à la liberté d'information de Hesse. Aucune décision automatisée n'a d'effet juridique ou similaire significatif."]
  ]
} satisfies AuditUi;

export const auditUi = { de, en, fr } satisfies Record<Locale, typeof de>;
