import type { Locale } from "./config";

export const measurementCopy = {
  de: {
    title: "Dürfen wir diesen Berichtaufruf zählen?",
    explanation: "Mit Ihrer freiwilligen Zustimmung erfasst Suchio diesen Aufruf für den angeschriebenen Betrieb, um die Briefaktion auszuwerten. Gespeichert werden Berichtkennung, Tag und Einwilligungsnachweis für 30 Tage, keine IP-Adresse in der Auswertung. Ein Widerrufsschlüssel bleibt dafür bis zu 30 Tage in diesem Browser. Der Bericht ist auch ohne Zustimmung vollständig lesbar.",
    accept: "Aufruf zählen erlauben", decline: "Ohne Zählung weiterlesen", withdraw: "Zustimmung widerrufen und Zählung löschen",
    accepted: "Ihre Zustimmung ist gespeichert. Sie können sie hier jederzeit widerrufen.", declined: "Dieser Aufruf wird nicht gezählt.",
    error: "Die Änderung konnte nicht bestätigt werden. Bitte erneut versuchen. Der Bericht bleibt verfügbar.", privacy: "Datenschutz zur Auswertung", preview: "Vorschau: Dieser Aufruf wird nicht gezählt.",
    privacyTitle: "Freiwillige Auswertung der Audit-Aufrufe",
    privacyBody: "Verantwortlich ist Aleks Tsenov, Suchio, mit den oben genannten Kontaktdaten. Nur wenn Sie im Bericht ausdrücklich zustimmen, erfassen wir einen bestätigten Aufruf der jeweiligen Berichtkennung und den Kalendertag (UTC). Zweck ist die Bewertung unserer Briefaktion. Die Zuordnung zum angeschriebenen Betrieb kann Personenbezug haben; die Auswertung ist nicht anonym. Rechtsgrundlage ist Art. 6 Abs. 1 lit. a DSGVO und für den lokalen Widerrufsschlüssel Ihre Einwilligung nach § 25 Abs. 1 TDDDG. Ablehnung hat keine Nachteile für den Zugang zum Bericht. Es gibt keine geräteübergreifende Wiedererkennung, keine Tracking-Cookies und keine Speicherung von IP-Adressen oder Browserprofilen in dieser Messdatenbank. Der zufällige Schlüssel dient nur dem Widerruf und der Vermeidung doppelter Übermittlung dieses einzelnen bestätigten Aufrufs. Im Browser wird er höchstens 30 Tage für diesen Bericht vorgehalten; wir zählen bei späteren Besuchen nicht automatisch weiter. Nach Ablauf wird er beim nächsten Zugriff entfernt. In der Datenbank werden sein Hash, Berichtkennung, Tag, Ablaufzeit und die Fassung des Einwilligungstexts gespeichert. Sie können im selben Browser im Bericht mit einem Klick widerrufen; der zugehörige Eintrag wird dann gelöscht. Alternativ kontaktieren Sie contact@suchio.net unter Angabe des Berichts, insbesondere bei einem Browserwechsel. Ohne individuelle Zuordnung können wir die Messdaten des gesamten Berichts löschen. Die Rechtmäßigkeit vor dem Widerruf bleibt unberührt. Die Messdaten werden nach 30 Tagen aus der laufenden Auswertung ausgeschlossen und durch einen stündlichen Löschlauf entfernt; bei Kampagnenende werden sie ebenfalls gelöscht. Cloudflare stellt Hosting und Datenbank bereit. Der Verwaltungszugang ist durch eine eigene Anmeldung geschützt. Für berechtigte Administratoren speichern wir einen gehashten Sitzungsschlüssel und die Anmelde-E-Mail bis zu einer Stunde in der Datenbank sowie ein technisch notwendiges Sitzungscookie im Browser. Abmelden widerruft die Sitzung; abgelaufene Sitzungen werden stündlich gelöscht. Rechtsgrundlagen hierfür sind Art. 6 Abs. 1 lit. f DSGVO (Schutz der internen Auswertung) und § 25 Abs. 2 Nr. 2 TDDDG. Zur Abwehr von Anmeldeversuchen wird die IP-Adresse vorübergehend für die Zugriffsbeschränkung verarbeitet, nicht für die Besuchsauswertung. Die Datenbank ist auf den EU-Datenstandort beschränkt; das garantiert keine ausschließlich europäische Verarbeitung aller Hosting- und Zugangsdaten. Technische Sicherheitsprotokolle und zeitlich begrenzte Sicherungen unterliegen den Anbieterfristen; wiederhergestellte Daten werden vor erneuter Nutzung bereinigt. Angaben zum Anbieter, zu Übermittlungen und zu Ihren Rechten stehen in dieser Datenschutzerklärung. Nur der berechtigte Suchio-Zugang sieht die Auswertung. Sie löst keine automatische Kontaktaufnahme oder Entscheidung aus. Bestätigte Aufrufe sind keine eindeutigen Leser und kein Nachweis einer Anfrage."
  },
  en: {
    title: "May we count this report visit?",
    explanation: "With your voluntary consent, Suchio records this visit for the business addressed to evaluate the postal campaign. We store the report code, day and consent evidence for 30 days, without an IP address in the statistics. A locally stored withdrawal key is valid for 30 days. The full report remains available without consent.",
    accept: "Allow this visit to be counted", decline: "Continue without counting", withdraw: "Withdraw consent and delete this count",
    accepted: "Your consent is stored. You can withdraw it here at any time.", declined: "This visit is not counted.",
    error: "The change could not be confirmed. Please try again. The report remains available.", privacy: "Measurement privacy information", preview: "Preview: this visit is not counted.",
    privacyTitle: "Optional measurement of audit visits",
    privacyBody: "The controller is Aleks Tsenov, Suchio, using the contact details above. Only after your explicit consent in the report do we record its code and the calendar day (UTC) to evaluate our postal campaign. The association with the addressed business may identify a person; these statistics are not anonymous. The legal bases are Article 6(1)(a) GDPR and, for the local withdrawal key, consent under section 25(1) TDDDG. Declining does not restrict the report. No cross-device recognition, tracking cookies, IP addresses or browser profiles are stored in the measurement database. A random key is used only for withdrawal and to avoid duplicate submission of this single confirmed visit. The locally stored key is valid for this report for 30 days; later visits are not automatically counted. An expired key is removed on the next access. The database stores its hash, report code, day, expiry and consent-text version. Withdraw with one click in the report in the same browser to delete the entry, or contact contact@suchio.net identifying the report, particularly after changing browsers. If individual attribution is unavailable, we can delete that report's entire measurement data. Withdrawal does not affect prior lawful processing. Records leave the active statistics after 30 days and are deleted by an hourly job, and also at campaign closure. Cloudflare supplies hosting and the database. Our own login protects administration. For authorised administrators, we store a hashed session key and login email for up to one hour and use a strictly necessary session cookie. Logout revokes the session; expired sessions are deleted hourly. The legal bases are Article 6(1)(f) GDPR (protecting internal statistics) and section 25(2)(2) TDDDG. IP addresses are processed temporarily to limit login attempts, not for visitor measurement. The database uses an EU jurisdiction; this does not mean all hosting and access data are processed exclusively in Europe. Security logs and time-limited backups follow provider retention periods; restored data are purged before reuse. Provider, transfer and rights information appears in this privacy policy. Only the authorised Suchio account sees the statistics. They trigger no automatic contact or decision. Confirmed visits do not identify unique readers or prove an enquiry."
  },
  fr: {
    title: "Pouvons-nous compter cette consultation ?",
    explanation: "Avec votre accord facultatif, Suchio compte cette consultation pour l’entreprise destinataire afin d’évaluer le courrier publicitaire. L’identifiant du rapport, le jour et la preuve du consentement sont conservés 30 jours, sans adresse IP dans les statistiques. Une clé de retrait reste dans ce navigateur jusqu’à 30 jours. Le rapport complet reste accessible sans accord.",
    accept: "Autoriser le comptage", decline: "Continuer sans comptage", withdraw: "Retirer l’accord et supprimer ce comptage",
    accepted: "Votre accord est enregistré. Vous pouvez le retirer ici à tout moment.", declined: "Cette consultation n’est pas comptée.",
    error: "La modification n’a pas pu être confirmée. Réessayez. Le rapport reste accessible.", privacy: "Confidentialité de la mesure", preview: "Aperçu : cette consultation n’est pas comptée.",
    privacyTitle: "Mesure facultative des consultations d’audit",
    privacyBody: "Le responsable est Aleks Tsenov, Suchio, aux coordonnées indiquées ci-dessus. Uniquement après votre consentement explicite dans le rapport, nous enregistrons son identifiant et le jour civil (UTC) pour évaluer notre campagne postale. Le lien avec l’entreprise destinataire peut identifier une personne ; ces statistiques ne sont pas anonymes. Les bases juridiques sont l’article 6(1)(a) du RGPD et, pour la clé locale de retrait, le consentement selon le § 25(1) TDDDG. Refuser ne limite pas le rapport. Aucun suivi entre appareils, cookie de suivi, adresse IP ou profil de navigateur n’est enregistré dans la base de mesure. Une clé aléatoire sert uniquement au retrait et à éviter une double transmission de cette consultation confirmée. Elle reste dans ce navigateur pour ce rapport jusqu’à 30 jours ; les consultations suivantes ne sont pas comptées automatiquement. La clé expirée est supprimée au prochain accès. La base conserve son empreinte, l’identifiant du rapport, le jour, l’expiration et la version du texte de consentement. Le retrait se fait en un clic dans le rapport avec le même navigateur et supprime l’entrée. Vous pouvez aussi contacter contact@suchio.net en précisant le rapport, notamment après un changement de navigateur. Sans attribution individuelle, nous pouvons supprimer toutes les mesures du rapport. Le retrait ne remet pas en cause la licéité du traitement antérieur. Les entrées quittent les statistiques actives après 30 jours et sont supprimées par une tâche horaire, ainsi qu’à la clôture de la campagne. Cloudflare fournit l’hébergement et la base. Une connexion propre au site protège l’administration. Pour les administrateurs autorisés, nous conservons l’empreinte d’une clé de session et l’adresse de connexion pendant une heure au maximum, avec un cookie de session strictement nécessaire. La déconnexion révoque la session ; les sessions expirées sont supprimées chaque heure. Les bases juridiques sont l’article 6(1)(f) du RGPD (protection des statistiques internes) et le § 25(2)(2) TDDDG. Les adresses IP servent temporairement à limiter les tentatives de connexion, pas à mesurer les visites. La base est limitée à une juridiction UE ; cela ne garantit pas un traitement exclusivement européen de toutes les données d’hébergement et d’accès. Les journaux de sécurité et sauvegardes temporaires suivent les durées du fournisseur ; les données restaurées sont purgées avant réutilisation. Les informations sur le fournisseur, les transferts et vos droits figurent dans cette politique. Seul le compte Suchio autorisé voit les statistiques. Aucun contact ni décision automatique n’en découle. Ces consultations ne représentent pas des lecteurs uniques et ne prouvent aucune demande."
  }
} satisfies Record<Locale, Record<string, string>>;

// Keep this versioned text with the database consent_version for evidence.
export const measurementConsentVersion = "2026-09-26-v1";
